# Week 3 Day 3 — Patient Monitoring Dashboard

## ICU Early Warning Prediction System

The objective of this stage is to transform the dashboard into an interactive ICU monitoring tool.

The dashboard will allow clinicians to:

- monitor individual patients,
- review predicted sepsis risk,
- identify high-risk cases,
- prioritize critical patients,
- support clinical decision-making.

In [7]:
import pandas as pd
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

In [8]:
PROJECT_ROOT = Path.cwd().parent

DASHBOARD_DATA_DIR = PROJECT_ROOT / "dashboard_data"

print("Dashboard data exists:", DASHBOARD_DATA_DIR.exists())

Dashboard data exists: True

In [9]:
patient_predictions = pd.read_csv(
    DASHBOARD_DATA_DIR / "dashboard_patient_predictions.csv"
)

top_10_patients = pd.read_csv(
    DASHBOARD_DATA_DIR / "dashboard_top_10_high_risk_patients.csv"
)

print("Patient predictions shape:", patient_predictions.shape)
print("Top 10 shape:", top_10_patients.shape)

Patient predictions shape: (100, 7)
Top 10 shape: (10, 7)

In [10]:
patient_predictions.head()

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review
1,p000042,1,1,0.999322,99.932154,Critical Risk,Urgent Clinical Review
2,p000028,1,1,0.999261,99.926142,Critical Risk,Urgent Clinical Review
3,p000009,1,1,0.999256,99.925559,Critical Risk,Urgent Clinical Review
4,p000018,1,1,0.998852,99.885235,Critical Risk,Urgent Clinical Review

In [11]:
top_10_patients

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review
1,p000042,1,1,0.999322,99.932154,Critical Risk,Urgent Clinical Review
2,p000028,1,1,0.999261,99.926142,Critical Risk,Urgent Clinical Review
3,p000009,1,1,0.999256,99.925559,Critical Risk,Urgent Clinical Review
4,p000018,1,1,0.998852,99.885235,Critical Risk,Urgent Clinical Review
5,p000034,1,1,0.998820,99.881973,Critical Risk,Urgent Clinical Review
6,p000056,1,1,0.998790,99.879013,Critical Risk,Urgent Clinical Review
7,p000015,1,1,0.998649,99.864915,Critical Risk,Urgent Clinical Review
8,p000058,1,1,0.998407,99.840659,Critical Risk,Urgent Clinical Review
9,p000011,1,1,0.997558,99.755789,Critical Risk,Urgent Clinical Review

In [12]:
high_risk = patient_predictions[
    patient_predictions["Risk_Category"].isin(
        ["High Risk", "Critical Risk"]
    )
]

print("High/Critical patients:", len(high_risk))

high_risk.head()

High/Critical patients: 17

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review
1,p000042,1,1,0.999322,99.932154,Critical Risk,Urgent Clinical Review
2,p000028,1,1,0.999261,99.926142,Critical Risk,Urgent Clinical Review
3,p000009,1,1,0.999256,99.925559,Critical Risk,Urgent Clinical Review
4,p000018,1,1,0.998852,99.885235,Critical Risk,Urgent Clinical Review

## Clinical Interpretation

Displaying patient-level predictions allows clinicians to quickly identify individuals requiring closer monitoring.

Separating high-risk patients improves prioritization and may support earlier intervention.

The Top 10 highest-risk patients can assist ICU teams during clinical review and resource allocation.