# Week 3 Day 4 — Patient Search and Filtering

## ICU Early Warning Prediction System

The objective of this stage is to improve dashboard usability by allowing clinicians to quickly locate specific patients and filter the monitoring view based on risk categories.

These functionalities support efficient clinical workflows by reducing the time required to identify patients requiring attention.

In [1]:
import pandas as pd
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
PROJECT_ROOT = Path.cwd().parent

DASHBOARD_DATA_DIR = PROJECT_ROOT / "dashboard_data"

patient_predictions = pd.read_csv(
    DASHBOARD_DATA_DIR / "dashboard_patient_predictions.csv"
)

print("Patient predictions shape:", patient_predictions.shape)

patient_predictions.head()

Patient predictions shape: (100, 7)

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review
1,p000042,1,1,0.999322,99.932154,Critical Risk,Urgent Clinical Review
2,p000028,1,1,0.999261,99.926142,Critical Risk,Urgent Clinical Review
3,p000009,1,1,0.999256,99.925559,Critical Risk,Urgent Clinical Review
4,p000018,1,1,0.998852,99.885235,Critical Risk,Urgent Clinical Review

In [3]:
patient_predictions["Risk_Category"].value_counts()

Risk_Category
Low Risk         81
Critical Risk    17
Moderate Risk     2
Name: count, dtype: int64

In [4]:
sample_patient = patient_predictions.iloc[0]["Patient_ID"]

searched_patient = patient_predictions[
    patient_predictions["Patient_ID"] == sample_patient
]

searched_patient

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review

In [5]:
critical_patients = patient_predictions[
    patient_predictions["Risk_Category"] == "Critical Risk"
]

print("Critical patients:", len(critical_patients))

critical_patients.head()

Critical patients: 17

,Patient_ID,True_Sepsis_Label,Predicted_Sepsis_Label,Sepsis_Probability,Risk_Score_Percent,Risk_Category,Clinical_Alert_Level
0,p000053,1,1,0.999427,99.942674,Critical Risk,Urgent Clinical Review
1,p000042,1,1,0.999322,99.932154,Critical Risk,Urgent Clinical Review
2,p000028,1,1,0.999261,99.926142,Critical Risk,Urgent Clinical Review
3,p000009,1,1,0.999256,99.925559,Critical Risk,Urgent Clinical Review
4,p000018,1,1,0.998852,99.885235,Critical Risk,Urgent Clinical Review

## Clinical Interpretation

Searching by Patient ID enables clinicians to rapidly retrieve individual patient information.

Filtering by risk category supports prioritization by focusing attention on high-risk populations.

These capabilities improve dashboard efficiency and simulate common functionalities found in hospital monitoring systems.